-- MySQL Script generated by MySQL Workbench
-- Tue Nov 20 14:46:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema compbiomed
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema compbiomed
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `compbiomed` DEFAULT CHARACTER SET utf8 ;
USE `compbiomed` ;

-- -----------------------------------------------------
-- Table `compbiomed`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compbiomed`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `active` TINYINT(1) NULL,
  `confirmed_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compbiomed`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compbiomed`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compbiomed`.`roles_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compbiomed`.`roles_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_roles_users_role_idx` (`role_id` ASC),
  INDEX `fk_roles_users_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_roles_users_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `compbiomed`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_users_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `compbiomed`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compbiomed`.`SERVICE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compbiomed`.`SERVICE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `scheduler_url` VARCHAR(256) NOT NULL,
  `username` VARCHAR(128) NULL DEFAULT NULL,
  `user_pass` VARCHAR(128) NULL DEFAULT NULL,
  `user_key` VARCHAR(256) NULL DEFAULT NULL,
  `file_url` VARCHAR(256) NULL,
  `working_directory` VARCHAR(256) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compbiomed`.`INPUT_SET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compbiomed`.`INPUT_SET` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_INPUT_SET_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_INPUT_SET_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `compbiomed`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compbiomed`.`JOB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compbiomed`.`JOB` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NULL DEFAULT 'NEW',
  `user_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  `input_set_id` INT NULL,
  `local_job_id` VARCHAR(128) NOT NULL,
  `remote_job_id` VARCHAR(256) NULL DEFAULT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `executable` VARCHAR(256) NULL DEFAULT NULL,
  `arguments` VARCHAR(256) NULL DEFAULT NULL,
  `env` VARCHAR(45) NULL DEFAULT NULL,
  `num_total_cpus` INT NULL DEFAULT NULL,
  `total_physical_memory` VARCHAR(45) NULL DEFAULT NULL,
  `working_directory` VARCHAR(256) NULL DEFAULT NULL,
  `wallclock_limit` VARCHAR(45) NULL DEFAULT NULL,
  `project` VARCHAR(45) NULL DEFAULT NULL,
  `queue` VARCHAR(45) NULL DEFAULT NULL,
  `extended` VARCHAR(1024) NULL DEFAULT NULL,
  `retrieved` TINYINT(1) NULL DEFAULT 0,
  `filter` VARCHAR(512) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_JOBS_user1_idx` (`user_id` ASC),
  INDEX `fk_JOBS_SERVICES1_idx` (`service_id` ASC),
  INDEX `fk_JOB_INPUT_SET1_idx` (`input_set_id` ASC),
  UNIQUE INDEX `local_job_id_UNIQUE` (`local_job_id` ASC),
  CONSTRAINT `fk_JOBS_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `compbiomed`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JOBS_SERVICES1`
    FOREIGN KEY (`service_id`)
    REFERENCES `compbiomed`.`SERVICE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JOB_INPUT_SET1`
    FOREIGN KEY (`input_set_id`)
    REFERENCES `compbiomed`.`INPUT_SET` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compbiomed`.`INPUT_SET_FILE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compbiomed`.`INPUT_SET_FILE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `description` VARCHAR(128) NULL,
  `input_set_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_INPUT_SET_FILE_INPUT_SET1_idx` (`input_set_id` ASC),
  CONSTRAINT `fk_INPUT_SET_FILE_INPUT_SET1`
    FOREIGN KEY (`input_set_id`)
    REFERENCES `compbiomed`.`INPUT_SET` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
